### ISSUE TITLE
Comments are not aligned with code

### ISSUE THREAD

**Issue by luyao** [huaweicloud/huaweicloud-sdk-go-v3#36] opened 2022-01-04 13:31 UTC
https://github.com/huaweicloud/huaweicloud-sdk-go-v3/blob/47b2ac3fa18c572c9d4aa1e9ba28c2419217b16a/services/iam/v3/model/model_update_user_option.go#L11

Comments or godoc should go with code, otherwise it will make clients confused.

**Comment by mawenbo-huawei** [comment] 2022-01-11 08:42
This issue is expected to be fixed in the next version. Thank you for your feedback.

**Comment by unionsdk** [comment] 2024-02-05 03:29
*长时间未收到回复，自动关闭问题。如有疑问，请重新打开问题或者创建新的问题。*
*If no reply is received for a long time, the issue is automatically closed.*
*If you have any questions, please reopen the issue or create a new issue.*

**Comment by Huaweicloud-SDK** [comment] 2024-02-05 03:56
*长时间未收到回复，自动关闭问题。如有疑问，请重新打开问题或者创建新的问题。*
*If no reply is received for a long time, the issue is automatically closed.*
*If you have any questions, please reopen the issue or create a new issue.*

**Closed by Huaweicloud-SDK** 2024-02-05 03:56 UTC
